apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator-long
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator-long
  template:
    metadata:
      labels:
        name: memcached-operator-long
    spec:
      serviceAccountName: memcached-operator-long
      containers:
        - name: memcached-operator-long
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - memcached-operator-long
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memcached-operator-long"
